### ISSUE TITLE
some questions about model effect

### ISSUE THREAD

**Issue by H-H-J** [drawbridge/keras-mmoe#12]
Hi, thanks for your share. Have you ever encountered the following problem？When the average predictive value of one task is 0.74, the value of the other task is as high as 0.92. However, the proportion of positive samples of this task is only about 12.5%. Whether the label column of the previous task (the predicted average value is 0.74) affected the second task?

**Comment by alvin319** [comment]
Hi! I don't know if I can answer that question given this observation that the modeling effect is highly correlated with the dataset itself.
