### ISSUE TITLE
How to solve the both regression task and classification task by MMOE model

### ISSUE THREAD

**Issue by zoe218** [drawbridge/keras-mmoe#17]
Hi~

I want to combine regression task and classification task in one model, but I found the regression loss and classification loss are so different, so it's too hard to optimize?

Can you give me some advice to handle this problem?
Thx~~

**Comment by alvin319** [comment]
Hello - one piece of advice that I would give is that multi-task learning is most useful when there is some correlation between your classification and regression tasks. You might want to try to inspect its Spearman/Pearson correlation on your labels to see if that's the case.
